### ISSUE TITLE
Slurm can't find themes

### ISSUE THREAD

**Issue by xtavras** [mattthias/slurm#1]
See Title. Tested on Debian Squeeze and Ubuntu 12.04 LTS. 

bob@bob-nb:/tmp$ ls /usr/share/slurm/
black.theme  blue.theme  cyan.theme  foo.theme
bob@bob-nb:/tmp$ slurm -t blue -i eth0
FATAL: cannot find theme 'blue'
bob@bob-nb:/tmp$ slurm -t blue.theme -i eth0
FATAL: cannot find theme 'blue.theme'

**Comment by jean** [comment]
I just ran into this on Ubuntu 14.04 ... slurm Version: 0.4.0-1

**Comment by mattthias** [comment]
Hi @jean, 
if fixed that problem in the slurm 0.4.1-1 package (in October 2014).  Please try to install the a newer version. If that is not possible please create a symbolic link as xtavras suggested: 

        ln -s /usr/share/slurm /usr/local/share/slurm

best wishes,
Matthias
