### ISSUE TITLE
Interface Speed

### ISSUE THREAD

**Issue by region51** [mattthias/slurm#12]
_Interface speed always unknown, why?_

**Comment by anarcat** [comment]
it looks like it's not implemented on Linux yet:

https://github.com/mattthias/slurm/blob/d4d13ac43a09b018ed123e24bc44d4ded90188a8/src/if_media.c#L299-L305

**Comment by anarcat** [comment]
patch available in #29

**Comment by mattthias** [comment]
Thanks @anarcat for the patch!
