### ISSUE TITLE
Where can I find theme for -t

### ISSUE THREAD

**Issue by starkshaw** [mattthias/slurm#14]
Under iTerm 2, oh-my-zsh, and OS X El Capitan.

**Comment by ryan-sg** [comment]
better late than never? :-)

the themes directory that comes with the source distribution of slurm is here
https://github.com/mattthias/slurm/tree/upstream/themes

On your machine, create a `~/.slurm` directory and copy those theme files there.

After that, you can call slurm like this to choose which theme you want:
`$ slurm -t blue`

**Comment by mattthias** [comment]
Hi @starkshaw , hi @ryan-sg , 

the hard-coded paths where slurm searches its themes is now replaced with a path inside the installation prefix. 
That should hopefully fix the issues with finding the themes in "non-standard" installation pathes.

https://github.com/mattthias/slurm/commit/58655d719dc3b79d9e90b1ca9c7eed890a87a1b8
