### ISSUE TITLE
Another program is already named "slurm"

### ISSUE THREAD

**Issue by isarandi** [mattthias/slurm#25]
Not sure if you know, but a workload manager (batch job scheduler) program is already called "[slurm](https://slurm.schedmd.com/)", which could lead to confusion.

**Comment by bjornfor** [comment]
This project was just packaged in nixpkgs. It was named `slurm-nm` to avoid clash with the above mentioned slurm package, but the binary is `slurm`. Consider me confused.

Random name suggestion: slum. It's like slurm but with a "kerning" typo :-)
