### ISSUE TITLE
Linux mint repository update

### ISSUE THREAD

**Issue by StevenMacias** [mattthias/slurm#35]
I have an Alpha Network AWUS036AC card. I noticed that if I install slurm in my Linux Mint 19.3 Tricia using apt-get  and then execute the following command:

`slurm -i wlx00c0caab7777` // Last 4 chars changed on purpose

In the Active Interface section of **slurm 0.4.3** only appears `wlx00c0ca` and rarely shows some peaks in the graph.

However, if I clone the repository from GitHub, compile it and execute the same command in **slurm 0.4.3+git**  it works perfectly and the Active Interface appears without being trimmed. 

Is there any way to request an update in the Linux Mint repositories? 

Thanks!

**Comment by mattthias** [comment]
Hi @StevenMacias  ,

as Mint based on Debian / Ubuntu it will get the updated slurm package when i manage to updated it. I have no real time frame for this but over the course of the last five years enough changes in the repo happened that justify a new release of slurm and therefore a new package. 
The bug you mention (interface name got truncated) was fixed a while ago : https://github.com/mattthias/slurm/pull/24 

Thanks for reporting this bug and using slurm :-)
