### ISSUE TITLE
fails with SIGSEGV

### ISSUE THREAD

**Issue by prspkt** [mattthias/slurm#36]
After a quick build on alpine linux, `slurm`  seems to consistently segfault during runtime.
Stepping through with `gdb` the error happens [here](https://github.com/mattthias/slurm/blob/upstream/src/linux.c#L66) with `BUFSIZ - 1` being greater than `BUFSIZE`.

Applying [this patch](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/13137/diffs#diff-content-699af1a6ce2efe747f5860b46d93f7ba9b9656d0) seems to fix the issue.

**Comment by mattthias** [comment]
Hi, 

the answer might come a year to late :-)

`BUFSIZ` is a macro that is defined in stdio.h (glibc 8192 / musl 1024)  and `BUFSIZE` is set to 256 in `src/linux.h`. 

The fgets tries to read max `BUFSIZ-1`  (on my amd64 with glibc  8191) chars into a buffer that is only `BUFSIZE` (256) chars big.      

That indeed looks wrong. I was wondering how this could ever work but looking at the first two lines of `/proc/net/dev` i see that this lines only ~125 chars long. If your slurm really crashes on this code line i would like to see the content of `/proc/net/dev`.
But in the actual interface / data lines i can imagine that we can reach a line lengths of more then 256 chars.

**Comment by klockeph** [comment]
I just installed slurm on arch linux from the AUR (https://aur.archlinux.org/packages/slurm/) and I experience a similar behaviour; it segfaults after a few seconds of runtime.
While I did not investigate with gdb yet, I imagine it could be the same issue. my `proc/net/dev` looks like the following

```
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo: 391504450597 8543650    0    0    0     0          0         0 391504450597 8543650    0    0    0     0       0          0
enp2s0f0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
wlp3s0: 132889587  223204    0  529    0     0          0         0 32549645   67318    0    0    0     0       0          0
docker0: 144529703   98316    0    0    0     0          0         0 337031942   58305    0    0    0     0       0          0
veth6a04989: 145906127   98316    0    0    0     0          0         0 337033088   58320    0    0    0     0       0          0

```

**Comment by mattthias** [comment]
Hello @klockeph &  @prspkt ,

the issue was solved by this https://github.com/mattthias/slurm/commit/43ed060bad728385f4b815a334b116e5a23e3c12  


Thanks for your report (even i have a horrible lag in answering / fixing stuff).
