### ISSUE TITLE
Release prep 0.4.4

### ISSUE THREAD

**Issue by nostalgia-for-infinity** [mattthias/slurm#40]
- [X] test Linux (Debian, Centos)
- [x] test alpine
- [x] test FreeBSD
- [x] test OpenBSD
- [ ] test MacOS

FreeBSD removed FDDI support : https://reviews.freebsd.org/D15170?id=41783 
  ->  Is it still used other *BSD?  Remove FDDI complete or work around?  DROPPED

**Comment by mattthias** [comment]
OpenBSD: 
 - Some patches are necessary : https://github.com/openbsd/ports/tree/master/net/slurm/patches
 - meson.build: dependency to curses instead ncurses
