### ISSUE TITLE
Graph view glitches

### ISSUE THREAD

**Issue by Iksas** [mattthias/slurm#41]
There are "stuck" elements in the top right corner of the graph. This happens in all three display modes (split, large and classic). 

The glitch is 100% reproducible on Raspberry Pi OS (Buster). It appears immediately after starting slurm, and looks looks different depending on the theme used.

Black theme:
![slurm_glitch_2](https://user-images.githubusercontent.com/17005217/142948448-705e9c57-cc32-4193-88d5-44d393612a73.png)

Default theme:
![slurm_default](https://user-images.githubusercontent.com/17005217/142949139-7c13d694-47f2-4d1b-b82b-ef16b376d340.png)

Blue theme:
![slurm_blue](https://user-images.githubusercontent.com/17005217/142949160-aa4d6f8c-177b-4fe6-93e4-4dd57ce2a527.png)

**Comment by mattthias** [comment]
Hi @Iksas ,

from the screenshot i guess you run the slurm package from the Debian / RaspbianOS repo? What terminal emulator do you use?

**Comment by Iksas** [comment]
Correct, it's Raspbian. 

I'm using the default terminal on macOS Bug Sur (11.6.1) via SSH.

**Comment by mattthias** [comment]
Hey @Iksas ,

I was able to reproduce the issue, even with Linux and xterm / gnome-terminal. Now i need to figure out why this happens.

**Comment by Iksas** [comment]
Possibly related: On macOS, the glitches don't occur, but instead the network graph never completely returns to zero when there is no traffic. A single spike remains, and reappears in the beginning of the graph every time it reaches the end: 

<img width="559" alt="bogus traffic" src="https://user-images.githubusercontent.com/17005217/152646119-f4911fbd-929d-4266-818a-8075f2e378fa.png">

Seems like there is some incorrect array handling going on. 
(To stop all traffic, I disconnected from the WiFi network)

**Comment by Iksas** [comment]
The bug is fixed on the latest `upstream` branch, so I'm closing this issue.
