### ISSUE TITLE
Update Documentation to support CentOS 6

### ISSUE THREAD

**Issue by jdrews** [mattthias/slurm#6]
I successfully compiled your software with CentOS 6.6. Here's my steps.

run as root:

yum install git
yum groupinstall 'Development Tools'
yum install ncurses-devel scons
git clone https://github.com/mattthias/slurm.git
cd slurm
scons
cp slurm /usr/bin

And now you can run slurm from anywhere.

**Comment by mattthias** [comment]
Hi @jdrews,

i updated the documentation; please have a look :-).

Best wishes,
Matthias
