### ISSUE TITLE
Name clash with another OSS project

### ISSUE THREAD

**Issue by mtds** [mattthias/slurm#7]
This may not be an issue (and I apologize for being pedantic) but you should 
probably be aware that your project has the same name of another one:

https://computing.llnl.gov/linux/slurm/ (A Highly Scalable Resource Manager)

Since I am working with HPC clusters when I saw your project I thought that
the development team has decided to add another feature :-).

**Comment by mattthias** [comment]
Hi mtds!

I know "the other slurm" but i'am not sure which one gets its name first. The development of slurm (the network monitor) goes back to 2002 and is named after the famous drink of Futurama (http://en.wikipedia.org/wiki/Fry_and_the_Slurm_Factory) :-).

In Debian and Ubuntu both programs are available; as "slurm" and as "slurm-llnl". So i guess the naming is no real issue.

Thanks for the report and best wishes,
Matthias
