### ISSUE TITLE
New compiling instructions

### ISSUE THREAD

**Issue by 9oLHhgeK** [mattthias/slurm#8]
**Updated Installation Instructions**, by Nathan McAneney

Requirements: scons

1. Download as a zip, this will give the file "slurm-upstream.zip"

2. Extract the zip to a directory:
      >$ unzip ~/Downloads/slurm-upstream.zip -d ~/Downloads

3. Navigate to this directory: 
      >$ cd ~/Downloads/slurm-upstream

4. Build the source with:
      >$ scons slurm

5. Move the executable file just created with scons to your /usr/bin directory:
      >$ sudo mv slurm /usr/bin

6. Finsihed, it will now work when you type:
      >$ slurm -i \<your_network_interface\>

**Comment by mattthias** [comment]
Hi @9oLHhgeK ,

i updated the documentation so please have a look :-).

best wishes,
Matthias
